### ISSUE TITLE
Translation to English?

### ISSUE THREAD

**Issue by Juvojic** [kabeor/Unicorn-Engine-Documentation#1]
Is it possible to translate this documentation to English?

**Comment by kabeor** [comment]
> Is it possible to translate this documentation to English?

I'd like to, however we're busy to code Qiling and Unicorn2 now.
I'll start as soon as possible. At the same time, I suggest you checking comments in the uc.c file or use google translate plugin:)

**Comment by migraine-sudo** [comment]
Hello, may I ask, how to solve such a problem? 
  Failed on uc_mem_map() with error returned 15 : Invalid argument (UC_ERR_ARG)
Code：
void map_memory(uint64_t addr,size_t size){
	//return !uc_mem_map(uc,addr,size,UC_PROT_ALL);
	uc_err err = uc_mem_map(uc,addr,size,UC_PROT_ALL);
    	
	    if (err) {
        	cout << ("Failed on uc_mem_map() with error returned ")
        	<< err << " : "<< uc_strerror(err) << endl;
        	//abort();
    	}
	}

**Comment by buzzer-re** [comment]
I did using google translate, check here on my gist:

https://gist.github.com/AandersonL/e4d8b09501127ceb15d72dcc2059d421
